/*
###############################################################
#  Generated by:      Cadence Encounter 14.28-s033_1
#  OS:                Linux x86_64(Host ID borax.clear.rice.edu)
#  Generated on:      Fri Apr  5 12:11:33 2019
#  Design:            UART
#  Command:           saveNetlist final.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : N-2017.09-SP2
// Date      : Fri Apr  5 12:04:21 2019
/////////////////////////////////////////////////////////////
module UART (
	clka, 
	clkb, 
	reset, 
	tx_data, 
	tx_rdy, 
	rx_rdy, 
	tx_busy, 
	tx_out, 
	tx_done, 
	tcount, 
	tstate, 
	tx_error, 
	tx_idle, 
	rx_busy, 
	rx_out, 
	rx_done, 
	rcount, 
	rstate, 
	rx_error, 
	rx_idle, 
	match, 
	rxrxout);
   input clka;
   input clkb;
   input reset;
   input [7:0] tx_data;
   input tx_rdy;
   input rx_rdy;
   output tx_busy;
   output [7:0] tx_out;
   output tx_done;
   output [3:0] tcount;
   output [3:0] tstate;
   output tx_error;
   output tx_idle;
   output rx_busy;
   output [7:0] rx_out;
   output rx_done;
   output [3:0] rcount;
   output [3:0] rstate;
   output rx_error;
   output rx_idle;
   output match;
   output [7:0] rxrxout;

   // Internal wires
   wire N0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire \tx/n144 ;
   wire \tx/n143 ;
   wire \tx/n142 ;
   wire \tx/n141 ;
   wire \tx/n140 ;
   wire \tx/n139 ;
   wire \tx/n138 ;
   wire \tx/n137 ;
   wire \tx/n136 ;
   wire \tx/n135 ;
   wire \tx/n134 ;
   wire \tx/n133 ;
   wire \tx/n132 ;
   wire \tx/n131 ;
   wire \tx/n130 ;
   wire \tx/n129 ;
   wire \tx/n128 ;
   wire \tx/n127 ;
   wire \tx/n126 ;
   wire \tx/n125 ;
   wire \tx/n124 ;
   wire \tx/n123 ;
   wire \tx/n122 ;
   wire \tx/n121 ;
   wire \tx/n120 ;
   wire \tx/n119 ;
   wire \tx/n118 ;
   wire \tx/n117 ;
   wire \tx/n116 ;
   wire \tx/n115 ;
   wire \tx/n114 ;
   wire \tx/n113 ;
   wire \tx/n112 ;
   wire \tx/n111 ;
   wire \tx/n110 ;
   wire \tx/n109 ;
   wire \tx/n108 ;
   wire \tx/n107 ;
   wire \tx/n106 ;
   wire \tx/n105 ;
   wire \tx/n104 ;
   wire \tx/n103 ;
   wire \tx/n102 ;
   wire \tx/n101 ;
   wire \tx/n100 ;
   wire \tx/n99 ;
   wire \tx/n98 ;
   wire \tx/n97 ;
   wire \tx/n95 ;
   wire \tx/n94 ;
   wire \tx/n93 ;
   wire \tx/n92 ;
   wire \tx/n91 ;
   wire \tx/n90 ;
   wire \tx/n89 ;
   wire \tx/n88 ;
   wire \tx/n87 ;
   wire \tx/n86 ;
   wire \tx/n85 ;
   wire \tx/n84 ;
   wire \tx/n83 ;
   wire \tx/n82 ;
   wire \tx/n81 ;
   wire \tx/n80 ;
   wire \tx/n79 ;
   wire \tx/n78 ;
   wire \tx/n77 ;
   wire \tx/n76 ;
   wire \tx/n75 ;
   wire \tx/n74 ;
   wire \tx/n73 ;
   wire \tx/n72 ;
   wire \tx/n71 ;
   wire \tx/n70 ;
   wire \tx/n69 ;
   wire \tx/n68 ;
   wire \tx/n67 ;
   wire \tx/n66 ;
   wire \tx/n65 ;
   wire \tx/n64 ;
   wire \tx/n63 ;
   wire \tx/n62 ;
   wire \tx/n61 ;
   wire \tx/n60 ;
   wire \tx/n59 ;
   wire \tx/n58 ;
   wire \tx/n57 ;
   wire \tx/n56 ;
   wire \tx/n55 ;
   wire \tx/n54 ;
   wire \tx/n53 ;
   wire \tx/n52 ;
   wire \tx/n51 ;
   wire \tx/n50 ;
   wire \tx/n49 ;
   wire \tx/n48 ;
   wire \tx/n47 ;
   wire \tx/n46 ;
   wire \tx/n45 ;
   wire \tx/n44 ;
   wire \tx/n43 ;
   wire \tx/n42 ;
   wire \tx/n41 ;
   wire \tx/n40 ;
   wire \tx/n39 ;
   wire \tx/n38 ;
   wire \tx/n37 ;
   wire \tx/n36 ;
   wire \tx/n35 ;
   wire \tx/n34 ;
   wire \tx/n33 ;
   wire \tx/n32 ;
   wire \tx/n31 ;
   wire \tx/n30 ;
   wire \tx/n29 ;
   wire \tx/n28 ;
   wire \tx/n27 ;
   wire \tx/n26 ;
   wire \tx/n25 ;
   wire \tx/n24 ;
   wire \tx/n23 ;
   wire \tx/n21 ;
   wire \tx/n20 ;
   wire \tx/n19 ;
   wire \tx/n18 ;
   wire \tx/n17 ;
   wire \tx/n16 ;
   wire \tx/n14 ;
   wire \tx/n13 ;
   wire \tx/n12 ;
   wire \tx/n11 ;
   wire \tx/n10 ;
   wire \tx/n9 ;
   wire \tx/N79 ;
   wire \tx/N78 ;
   wire \tx/N77 ;
   wire \rx/n152 ;
   wire \rx/n151 ;
   wire \rx/n150 ;
   wire \rx/n149 ;
   wire \rx/n148 ;
   wire \rx/n147 ;
   wire \rx/n146 ;
   wire \rx/n145 ;
   wire \rx/n144 ;
   wire \rx/n143 ;
   wire \rx/n142 ;
   wire \rx/n141 ;
   wire \rx/n140 ;
   wire \rx/n139 ;
   wire \rx/n138 ;
   wire \rx/n137 ;
   wire \rx/n136 ;
   wire \rx/n135 ;
   wire \rx/n134 ;
   wire \rx/n133 ;
   wire \rx/n132 ;
   wire \rx/n131 ;
   wire \rx/n130 ;
   wire \rx/n129 ;
   wire \rx/n128 ;
   wire \rx/n127 ;
   wire \rx/n126 ;
   wire \rx/n125 ;
   wire \rx/n124 ;
   wire \rx/n123 ;
   wire \rx/n122 ;
   wire \rx/n121 ;
   wire \rx/n120 ;
   wire \rx/n119 ;
   wire \rx/n118 ;
   wire \rx/n117 ;
   wire \rx/n116 ;
   wire \rx/n115 ;
   wire \rx/n114 ;
   wire \rx/n113 ;
   wire \rx/n112 ;
   wire \rx/n111 ;
   wire \rx/n110 ;
   wire \rx/n109 ;
   wire \rx/n108 ;
   wire \rx/n107 ;
   wire \rx/n106 ;
   wire \rx/n105 ;
   wire \rx/n104 ;
   wire \rx/n103 ;
   wire \rx/n102 ;
   wire \rx/n101 ;
   wire \rx/n100 ;
   wire \rx/n99 ;
   wire \rx/n98 ;
   wire \rx/n97 ;
   wire \rx/n96 ;
   wire \rx/n95 ;
   wire \rx/n94 ;
   wire \rx/n93 ;
   wire \rx/n92 ;
   wire \rx/n91 ;
   wire \rx/n90 ;
   wire \rx/n89 ;
   wire \rx/n88 ;
   wire \rx/n87 ;
   wire \rx/n86 ;
   wire \rx/n84 ;
   wire \rx/n83 ;
   wire \rx/n82 ;
   wire \rx/n81 ;
   wire \rx/n80 ;
   wire \rx/n79 ;
   wire \rx/n78 ;
   wire \rx/n77 ;
   wire \rx/n76 ;
   wire \rx/n75 ;
   wire \rx/n74 ;
   wire \rx/n73 ;
   wire \rx/n72 ;
   wire \rx/n71 ;
   wire \rx/n70 ;
   wire \rx/n69 ;
   wire \rx/n68 ;
   wire \rx/n67 ;
   wire \rx/n66 ;
   wire \rx/n65 ;
   wire \rx/n63 ;
   wire \rx/n62 ;
   wire \rx/n61 ;
   wire \rx/n60 ;
   wire \rx/n59 ;
   wire \rx/n58 ;
   wire \rx/n57 ;
   wire \rx/n56 ;
   wire \rx/n55 ;
   wire \rx/n54 ;
   wire \rx/n53 ;
   wire \rx/n52 ;
   wire \rx/n51 ;
   wire \rx/n50 ;
   wire \rx/n49 ;
   wire \rx/n48 ;
   wire \rx/n47 ;
   wire \rx/n46 ;
   wire \rx/n45 ;
   wire \rx/n44 ;
   wire \rx/n43 ;
   wire \rx/n42 ;
   wire \rx/n41 ;
   wire \rx/n40 ;
   wire \rx/n39 ;
   wire \rx/n38 ;
   wire \rx/n37 ;
   wire \rx/n36 ;
   wire \rx/n35 ;
   wire \rx/n34 ;
   wire \rx/n33 ;
   wire \rx/n32 ;
   wire \rx/n31 ;
   wire \rx/n30 ;
   wire \rx/n29 ;
   wire \rx/n28 ;
   wire \rx/n27 ;
   wire \rx/n26 ;
   wire \rx/n25 ;
   wire \rx/n23 ;
   wire \rx/n21 ;
   wire \rx/n20 ;
   wire \rx/n19 ;
   wire \rx/n18 ;
   wire \rx/n17 ;
   wire \rx/n16 ;
   wire \rx/n15 ;
   wire \rx/n14 ;
   wire \rx/n13 ;
   wire \rx/n12 ;
   wire \rx/n11 ;
   wire \rx/n10 ;
   wire \rx/n9 ;
   wire \rx/N79 ;
   wire \rx/N78 ;
   wire \rx/N77 ;
   wire \dp1/d1/n3 ;
   wire \dp1/d1/n1 ;
   wire \dp1/d1/N11 ;
   wire \dp1/d1/N10 ;
   wire \dp1/d1/N9 ;
   wire \dp1/d1/N8 ;
   wire \dp1/d1/N7 ;
   wire \dp1/d1/N6 ;
   wire \dp1/d1/N4 ;
   wire \dp1/d1/N3 ;
   wire \dp2/d1/N11 ;
   wire \dp2/d1/N10 ;
   wire \dp2/d1/N9 ;
   wire \dp2/d1/N8 ;
   wire \dp2/d1/N7 ;
   wire \dp2/d1/N6 ;
   wire \dp2/d1/N5 ;
   wire \dp2/d1/N4 ;
   wire \dp2/d1/N3 ;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire [7:0] rx_data;
   wire [7:2] \tx/ttmpout ;
   wire [3:0] \tx/next_tstate ;
   wire [7:2] \rx/rtmpout ;
   wire [3:0] \rx/next_rstate ;

   assign match = N0 ;

   NOR2X1 U1 (.Y(N0),
	.B(n2),
	.A(n1));
   NAND3X1 U2 (.Y(n2),
	.C(n5),
	.B(n4),
	.A(n3));
   NOR2X1 U3 (.Y(n5),
	.B(n7),
	.A(n6));
   XOR2X1 U4 (.Y(n7),
	.B(rxrxout[6]),
	.A(tx_data[6]));
   XOR2X1 U5 (.Y(n6),
	.B(rxrxout[7]),
	.A(tx_data[7]));
   XNOR2X1 U6 (.Y(n4),
	.B(rxrxout[3]),
	.A(tx_data[3]));
   XNOR2X1 U7 (.Y(n3),
	.B(rxrxout[2]),
	.A(tx_data[2]));
   NAND3X1 U8 (.Y(n1),
	.C(n10),
	.B(n9),
	.A(n8));
   NOR2X1 U9 (.Y(n10),
	.B(n12),
	.A(n11));
   XOR2X1 U10 (.Y(n12),
	.B(rxrxout[5]),
	.A(tx_data[5]));
   XOR2X1 U11 (.Y(n11),
	.B(rxrxout[4]),
	.A(tx_data[4]));
   XNOR2X1 U12 (.Y(n9),
	.B(rxrxout[0]),
	.A(tx_data[0]));
   XNOR2X1 U13 (.Y(n8),
	.B(rxrxout[1]),
	.A(tx_data[1]));
   OAI21X1 \tx/U142  (.Y(\tx/n116 ),
	.C(\tx/n32 ),
	.B(\tx/n46 ),
	.A(tstate[2]));
   NOR2X1 \tx/U141  (.Y(\tx/n118 ),
	.B(tstate[2]),
	.A(tx_busy));
   NAND3X1 \tx/U140  (.Y(\tx/n117 ),
	.C(\tx/n118 ),
	.B(\tx/n33 ),
	.A(tstate[1]));
   OR2X1 \tx/U139  (.Y(\tx/n112 ),
	.B(reset),
	.A(tstate[3]));
   AOI21X1 \tx/U138  (.Y(\tx/N77 ),
	.C(\tx/n112 ),
	.B(\tx/n117 ),
	.A(\tx/n116 ));
   NAND3X1 \tx/U137  (.Y(\tx/n115 ),
	.C(tx_rdy),
	.B(\tx/n32 ),
	.A(tstate[0]));
   OAI21X1 \tx/U136  (.Y(\tx/n114 ),
	.C(\tx/n115 ),
	.B(\tx/n32 ),
	.A(tstate[0]));
   NAND2X1 \tx/U135  (.Y(\tx/n113 ),
	.B(\tx/n31 ),
	.A(\tx/n114 ));
   NOR2X1 \tx/U134  (.Y(\tx/N78 ),
	.B(\tx/n113 ),
	.A(\tx/n112 ));
   NAND3X1 \tx/U133  (.Y(\tx/n110 ),
	.C(tstate[0]),
	.B(\tx/n31 ),
	.A(tstate[1]));
   NAND3X1 \tx/U132  (.Y(\tx/n111 ),
	.C(tstate[2]),
	.B(\tx/n32 ),
	.A(\tx/n33 ));
   AOI21X1 \tx/U131  (.Y(\tx/N79 ),
	.C(\tx/n112 ),
	.B(\tx/n111 ),
	.A(\tx/n110 ));
   NAND3X1 \tx/U130  (.Y(\tx/n83 ),
	.C(\tx/next_tstate [1]),
	.B(\tx/n25 ),
	.A(\tx/n27 ));
   NAND3X1 \tx/U129  (.Y(\tx/n97 ),
	.C(\tx/n27 ),
	.B(\tx/n25 ),
	.A(\tx/n26 ));
   NOR2X1 \tx/U126  (.Y(\tx/n105 ),
	.B(\tx/n21 ),
	.A(\tx/n83 ));
   OAI22X1 \tx/U125  (.Y(\tx/n144 ),
	.D(\tx/n18 ),
	.C(tcount[0]),
	.B(\tx/n107 ),
	.A(\tx/n39 ));
   NOR2X1 \tx/U124  (.Y(\tx/n81 ),
	.B(tcount[1]),
	.A(\tx/n36 ));
   NAND2X1 \tx/U123  (.Y(\tx/n86 ),
	.B(tcount[0]),
	.A(\tx/n81 ));
   NOR2X1 \tx/U122  (.Y(\tx/n104 ),
	.B(\tx/n36 ),
	.A(\tx/n37 ));
   NOR2X1 \tx/U121  (.Y(\tx/n109 ),
	.B(\tx/n104 ),
	.A(tcount[3]));
   NAND3X1 \tx/U120  (.Y(\tx/n108 ),
	.C(\tx/n109 ),
	.B(\tx/n86 ),
	.A(\tx/n105 ));
   OAI21X1 \tx/U119  (.Y(\tx/n143 ),
	.C(\tx/n108 ),
	.B(\tx/n30 ),
	.A(\tx/n107 ));
   AOI21X1 \tx/U118  (.Y(\tx/n99 ),
	.C(\tx/n21 ),
	.B(\tx/n24 ),
	.A(\tx/n39 ));
   OAI21X1 \tx/U117  (.Y(\tx/n106 ),
	.C(\tx/n99 ),
	.B(\tx/n104 ),
	.A(\tx/n83 ));
   NAND2X1 \tx/U116  (.Y(\tx/n102 ),
	.B(tcount[0]),
	.A(\tx/n105 ));
   NAND3X1 \tx/U115  (.Y(\tx/n103 ),
	.C(\tx/n104 ),
	.B(\tx/n34 ),
	.A(\tx/n19 ));
   OAI21X1 \tx/U114  (.Y(\tx/n142 ),
	.C(\tx/n103 ),
	.B(\tx/n34 ),
	.A(\tx/n20 ));
   OAI22X1 \tx/U113  (.Y(\tx/n141 ),
	.D(\tx/n102 ),
	.C(tcount[1]),
	.B(\tx/n37 ),
	.A(\tx/n99 ));
   NOR2X1 \tx/U112  (.Y(\tx/n101 ),
	.B(\tx/n37 ),
	.A(tcount[2]));
   AOI22X1 \tx/U111  (.Y(\tx/n100 ),
	.D(\tx/n81 ),
	.C(\tx/n24 ),
	.B(\tx/n19 ),
	.A(\tx/n101 ));
   OAI21X1 \tx/U110  (.Y(\tx/n140 ),
	.C(\tx/n100 ),
	.B(\tx/n36 ),
	.A(\tx/n99 ));
   NAND2X1 \tx/U109  (.Y(\tx/n98 ),
	.B(\tx/n21 ),
	.A(tx_idle));
   OAI21X1 \tx/U108  (.Y(\tx/n139 ),
	.C(\tx/n98 ),
	.B(\tx/n97 ),
	.A(\tx/n21 ));
   NAND3X1 \tx/U106  (.Y(\tx/n92 ),
	.C(\tx/n25 ),
	.B(\tx/next_tstate [0]),
	.A(\tx/next_tstate [1]));
   OAI21X1 \tx/U105  (.Y(\tx/n138 ),
	.C(\tx/n92 ),
	.B(\tx/n29 ),
	.A(\tx/n95 ));
   NAND3X1 \tx/U104  (.Y(\tx/n57 ),
	.C(\tx/next_tstate [2]),
	.B(\tx/n26 ),
	.A(\tx/next_tstate [0]));
   NOR2X1 \tx/U103  (.Y(\tx/n94 ),
	.B(\tx/n25 ),
	.A(\tx/n23 ));
   NAND3X1 \tx/U102  (.Y(\tx/n59 ),
	.C(\tx/next_tstate [2]),
	.B(\tx/n26 ),
	.A(\tx/n27 ));
   OAI22X1 \tx/U99  (.Y(\tx/n137 ),
	.D(\tx/n33 ),
	.C(\tx/n93 ),
	.B(\tx/n27 ),
	.A(\tx/n16 ));
   OAI22X1 \tx/U98  (.Y(\tx/n136 ),
	.D(\tx/n32 ),
	.C(\tx/n93 ),
	.B(\tx/n26 ),
	.A(\tx/n16 ));
   OAI22X1 \tx/U97  (.Y(\tx/n135 ),
	.D(\tx/n31 ),
	.C(\tx/n93 ),
	.B(\tx/n25 ),
	.A(\tx/n16 ));
   NAND2X1 \tx/U96  (.Y(\tx/n82 ),
	.B(\tx/n92 ),
	.A(\tx/n21 ));
   AOI22X1 \tx/U95  (.Y(\tx/n90 ),
	.D(tx_data[2]),
	.C(\tx/n39 ),
	.B(tcount[0]),
	.A(tx_data[3]));
   AOI22X1 \tx/U94  (.Y(\tx/n91 ),
	.D(tx_data[4]),
	.C(\tx/n39 ),
	.B(tcount[0]),
	.A(tx_data[5]));
   OAI22X1 \tx/U93  (.Y(\tx/n88 ),
	.D(\tx/n91 ),
	.C(\tx/n37 ),
	.B(tcount[1]),
	.A(\tx/n90 ));
   AOI22X1 \tx/U92  (.Y(\tx/n89 ),
	.D(tcount[0]),
	.C(tx_data[7]),
	.B(\tx/n39 ),
	.A(tx_data[6]));
   AOI22X1 \tx/U91  (.Y(\tx/n87 ),
	.D(\tx/n81 ),
	.C(\tx/n38 ),
	.B(\tx/n88 ),
	.A(\tx/n36 ));
   OR2X1 \tx/U90  (.Y(\tx/n85 ),
	.B(tcount[3]),
	.A(\tx/n86 ));
   OAI21X1 \tx/U89  (.Y(\tx/n84 ),
	.C(\tx/n82 ),
	.B(\tx/n85 ),
	.A(\tx/n35 ));
   OAI22X1 \tx/U88  (.Y(\tx/n133 ),
	.D(\tx/n84 ),
	.C(\tx/n83 ),
	.B(\tx/n82 ),
	.A(\tx/n40 ));
   NAND2X1 \tx/U86  (.Y(\tx/n80 ),
	.B(\tx/n39 ),
	.A(\tx/n81 ));
   OAI21X1 \tx/U85  (.Y(\tx/n79 ),
	.C(\tx/n97 ),
	.B(\tx/n80 ),
	.A(\tx/n78 ));
   NAND2X1 \tx/U84  (.Y(\tx/n69 ),
	.B(\tx/n35 ),
	.A(\tx/n24 ));
   OAI22X1 \tx/U83  (.Y(\tx/n132 ),
	.D(\tx/n69 ),
	.C(\tx/n10 ),
	.B(\tx/n79 ),
	.A(\tx/n41 ));
   OR2X1 \tx/U82  (.Y(\tx/n70 ),
	.B(tcount[2]),
	.A(\tx/n78 ));
   NAND2X1 \tx/U81  (.Y(\tx/n77 ),
	.B(tcount[0]),
	.A(tcount[1]));
   OAI21X1 \tx/U80  (.Y(\tx/n76 ),
	.C(\tx/n97 ),
	.B(\tx/n77 ),
	.A(\tx/n70 ));
   OAI22X1 \tx/U79  (.Y(\tx/n131 ),
	.D(\tx/n69 ),
	.C(\tx/n11 ),
	.B(\tx/n76 ),
	.A(\tx/n42 ));
   NAND2X1 \tx/U78  (.Y(\tx/n75 ),
	.B(\tx/n39 ),
	.A(tcount[1]));
   OAI21X1 \tx/U77  (.Y(\tx/n74 ),
	.C(\tx/n97 ),
	.B(\tx/n75 ),
	.A(\tx/n70 ));
   OAI22X1 \tx/U76  (.Y(\tx/n130 ),
	.D(\tx/n69 ),
	.C(\tx/n12 ),
	.B(\tx/n74 ),
	.A(\tx/n43 ));
   NAND2X1 \tx/U75  (.Y(\tx/n73 ),
	.B(\tx/n37 ),
	.A(tcount[0]));
   OAI21X1 \tx/U74  (.Y(\tx/n72 ),
	.C(\tx/n97 ),
	.B(\tx/n73 ),
	.A(\tx/n70 ));
   OAI22X1 \tx/U73  (.Y(\tx/n129 ),
	.D(\tx/n69 ),
	.C(\tx/n13 ),
	.B(\tx/n72 ),
	.A(\tx/n44 ));
   NAND2X1 \tx/U72  (.Y(\tx/n71 ),
	.B(\tx/n37 ),
	.A(\tx/n39 ));
   OAI21X1 \tx/U71  (.Y(\tx/n68 ),
	.C(\tx/n97 ),
	.B(\tx/n71 ),
	.A(\tx/n70 ));
   OAI22X1 \tx/U70  (.Y(\tx/n128 ),
	.D(\tx/n69 ),
	.C(\tx/n14 ),
	.B(\tx/n68 ),
	.A(\tx/n45 ));
   XOR2X1 \tx/U69  (.Y(\tx/n65 ),
	.B(tx_data[6]),
	.A(\tx/n41 ));
   XOR2X1 \tx/U68  (.Y(\tx/n66 ),
	.B(tx_data[5]),
	.A(\tx/n42 ));
   XOR2X1 \tx/U67  (.Y(\tx/n67 ),
	.B(tx_data[4]),
	.A(\tx/n43 ));
   NAND3X1 \tx/U66  (.Y(\tx/n61 ),
	.C(\tx/n67 ),
	.B(\tx/n66 ),
	.A(\tx/n65 ));
   XOR2X1 \tx/U65  (.Y(\tx/n63 ),
	.B(tx_data[3]),
	.A(\tx/n44 ));
   XOR2X1 \tx/U64  (.Y(\tx/n64 ),
	.B(tx_data[2]),
	.A(\tx/n45 ));
   NAND2X1 \tx/U63  (.Y(\tx/n62 ),
	.B(\tx/n64 ),
	.A(\tx/n63 ));
   OAI21X1 \tx/U62  (.Y(\tx/n60 ),
	.C(\tx/n58 ),
	.B(\tx/n62 ),
	.A(\tx/n61 ));
   OAI22X1 \tx/U61  (.Y(\tx/n127 ),
	.D(\tx/n60 ),
	.C(\tx/n59 ),
	.B(\tx/n58 ),
	.A(\tx/n28 ));
   NAND2X1 \tx/U59  (.Y(\tx/n47 ),
	.B(\tx/n56 ),
	.A(\tx/n23 ));
   NAND2X1 \tx/U58  (.Y(\tx/n55 ),
	.B(\tx/n9 ),
	.A(tx_out[0]));
   OAI21X1 \tx/U57  (.Y(\tx/n126 ),
	.C(\tx/n55 ),
	.B(\tx/n28 ),
	.A(\tx/n47 ));
   NAND2X1 \tx/U56  (.Y(\tx/n54 ),
	.B(\tx/n9 ),
	.A(tx_out[1]));
   OAI21X1 \tx/U55  (.Y(\tx/n125 ),
	.C(\tx/n54 ),
	.B(\tx/n29 ),
	.A(\tx/n47 ));
   NAND2X1 \tx/U54  (.Y(\tx/n53 ),
	.B(\tx/n9 ),
	.A(tx_out[2]));
   OAI21X1 \tx/U53  (.Y(\tx/n124 ),
	.C(\tx/n53 ),
	.B(\tx/n45 ),
	.A(\tx/n47 ));
   NAND2X1 \tx/U52  (.Y(\tx/n52 ),
	.B(\tx/n9 ),
	.A(tx_out[3]));
   OAI21X1 \tx/U51  (.Y(\tx/n123 ),
	.C(\tx/n52 ),
	.B(\tx/n44 ),
	.A(\tx/n47 ));
   NAND2X1 \tx/U50  (.Y(\tx/n51 ),
	.B(\tx/n9 ),
	.A(tx_out[4]));
   OAI21X1 \tx/U49  (.Y(\tx/n122 ),
	.C(\tx/n51 ),
	.B(\tx/n43 ),
	.A(\tx/n47 ));
   NAND2X1 \tx/U48  (.Y(\tx/n50 ),
	.B(\tx/n9 ),
	.A(tx_out[5]));
   OAI21X1 \tx/U47  (.Y(\tx/n121 ),
	.C(\tx/n50 ),
	.B(\tx/n42 ),
	.A(\tx/n47 ));
   NAND2X1 \tx/U46  (.Y(\tx/n49 ),
	.B(\tx/n9 ),
	.A(tx_out[6]));
   OAI21X1 \tx/U45  (.Y(\tx/n120 ),
	.C(\tx/n49 ),
	.B(\tx/n41 ),
	.A(\tx/n47 ));
   NAND2X1 \tx/U44  (.Y(\tx/n48 ),
	.B(\tx/n9 ),
	.A(tx_out[7]));
   OAI21X1 \tx/U43  (.Y(\tx/n119 ),
	.C(\tx/n48 ),
	.B(\tx/n40 ),
	.A(\tx/n47 ));
   INVX2 \tx/U42  (.Y(\tx/n46 ),
	.A(tx_rdy));
   INVX2 \tx/U41  (.Y(\tx/n45 ),
	.A(\tx/ttmpout [2]));
   INVX2 \tx/U40  (.Y(\tx/n44 ),
	.A(\tx/ttmpout [3]));
   INVX2 \tx/U39  (.Y(\tx/n43 ),
	.A(\tx/ttmpout [4]));
   INVX2 \tx/U38  (.Y(\tx/n42 ),
	.A(\tx/ttmpout [5]));
   INVX2 \tx/U37  (.Y(\tx/n41 ),
	.A(\tx/ttmpout [6]));
   INVX2 \tx/U36  (.Y(\tx/n40 ),
	.A(\tx/ttmpout [7]));
   INVX2 \tx/U35  (.Y(\tx/n39 ),
	.A(tcount[0]));
   INVX2 \tx/U34  (.Y(\tx/n38 ),
	.A(\tx/n89 ));
   INVX2 \tx/U33  (.Y(\tx/n37 ),
	.A(tcount[1]));
   INVX2 \tx/U32  (.Y(\tx/n36 ),
	.A(tcount[2]));
   INVX2 \tx/U31  (.Y(\tx/n35 ),
	.A(\tx/n87 ));
   INVX2 \tx/U30  (.Y(\tx/n34 ),
	.A(tcount[3]));
   INVX2 \tx/U29  (.Y(\tx/n33 ),
	.A(tstate[0]));
   INVX2 \tx/U28  (.Y(\tx/n32 ),
	.A(tstate[1]));
   INVX2 \tx/U27  (.Y(\tx/n31 ),
	.A(tstate[2]));
   INVX2 \tx/U26  (.Y(\tx/n30 ),
	.A(tx_busy));
   INVX2 \tx/U25  (.Y(\tx/n29 ),
	.A(tx_done));
   INVX2 \tx/U24  (.Y(\tx/n28 ),
	.A(tx_error));
   INVX2 \tx/U23  (.Y(\tx/n27 ),
	.A(\tx/next_tstate [0]));
   INVX2 \tx/U22  (.Y(\tx/n26 ),
	.A(\tx/next_tstate [1]));
   INVX2 \tx/U21  (.Y(\tx/n25 ),
	.A(\tx/next_tstate [2]));
   INVX2 \tx/U20  (.Y(\tx/n24 ),
	.A(\tx/n83 ));
   INVX2 \tx/U19  (.Y(\tx/n23 ),
	.A(\tx/n57 ));
   INVX2 \tx/U17  (.Y(\tx/n21 ),
	.A(\tx/n107 ));
   INVX2 \tx/U16  (.Y(\tx/n20 ),
	.A(\tx/n106 ));
   INVX2 \tx/U15  (.Y(\tx/n19 ),
	.A(\tx/n102 ));
   INVX2 \tx/U14  (.Y(\tx/n18 ),
	.A(\tx/n105 ));
   INVX2 \tx/U13  (.Y(\tx/n17 ),
	.A(\tx/n58 ));
   INVX2 \tx/U12  (.Y(\tx/n16 ),
	.A(\tx/n93 ));
   INVX2 \tx/U11  (.Y(\tx/n14 ),
	.A(\tx/n68 ));
   INVX2 \tx/U10  (.Y(\tx/n13 ),
	.A(\tx/n72 ));
   INVX2 \tx/U9  (.Y(\tx/n12 ),
	.A(\tx/n74 ));
   INVX2 \tx/U8  (.Y(\tx/n11 ),
	.A(\tx/n76 ));
   INVX2 \tx/U7  (.Y(\tx/n10 ),
	.A(\tx/n79 ));
   INVX2 \tx/U6  (.Y(\tx/n9 ),
	.A(\tx/n56 ));
   AND2X2 \tx/U5  (.Y(\tx/n134 ),
	.B(tstate[3]),
	.A(\tx/n16 ));
   DFFNEGX1 \tx/tx_out_reg[2]  (.Q(tx_out[2]),
	.D(\tx/n124 ),
	.CLK(clkb));
   DFFNEGX1 \tx/tx_out_reg[0]  (.Q(tx_out[0]),
	.D(\tx/n126 ),
	.CLK(clkb));
   DFFNEGX1 \tx/tx_error_reg  (.Q(tx_error),
	.D(\tx/n127 ),
	.CLK(clkb));
   DFFNEGX1 \tx/ttmpout_reg[2]  (.Q(\tx/ttmpout [2]),
	.D(\tx/n128 ),
	.CLK(clkb));
   DFFNEGX1 \tx/tx_out_reg[3]  (.Q(tx_out[3]),
	.D(\tx/n123 ),
	.CLK(clkb));
   DFFNEGX1 \tx/ttmpout_reg[3]  (.Q(\tx/ttmpout [3]),
	.D(\tx/n129 ),
	.CLK(clkb));
   DFFNEGX1 \tx/tx_out_reg[4]  (.Q(tx_out[4]),
	.D(\tx/n122 ),
	.CLK(clkb));
   DFFNEGX1 \tx/ttmpout_reg[4]  (.Q(\tx/ttmpout [4]),
	.D(\tx/n130 ),
	.CLK(n13));
   DFFNEGX1 \tx/tx_out_reg[5]  (.Q(tx_out[5]),
	.D(\tx/n121 ),
	.CLK(n14));
   DFFNEGX1 \tx/ttmpout_reg[5]  (.Q(\tx/ttmpout [5]),
	.D(\tx/n131 ),
	.CLK(n15));
   DFFNEGX1 \tx/tx_out_reg[6]  (.Q(tx_out[6]),
	.D(\tx/n120 ),
	.CLK(n13));
   DFFNEGX1 \tx/ttmpout_reg[6]  (.Q(\tx/ttmpout [6]),
	.D(\tx/n132 ),
	.CLK(n14));
   DFFNEGX1 \tx/tx_out_reg[7]  (.Q(tx_out[7]),
	.D(\tx/n119 ),
	.CLK(n15));
   DFFNEGX1 \tx/ttmpout_reg[7]  (.Q(\tx/ttmpout [7]),
	.D(\tx/n133 ),
	.CLK(n15));
   DFFNEGX1 \tx/tstate_reg[1]  (.Q(tstate[1]),
	.D(\tx/n136 ),
	.CLK(n15));
   DFFNEGX1 \tx/tstate_reg[3]  (.Q(tstate[3]),
	.D(\tx/n134 ),
	.CLK(n15));
   DFFNEGX1 \tx/tx_out_reg[1]  (.Q(tx_out[1]),
	.D(\tx/n125 ),
	.CLK(n15));
   DFFNEGX1 \tx/tx_idle_reg  (.Q(tx_idle),
	.D(\tx/n139 ),
	.CLK(n15));
   DFFNEGX1 \tx/tcount_reg[2]  (.Q(tcount[2]),
	.D(\tx/n140 ),
	.CLK(n15));
   DFFNEGX1 \tx/tcount_reg[1]  (.Q(tcount[1]),
	.D(\tx/n141 ),
	.CLK(n15));
   DFFNEGX1 \tx/tx_done_reg  (.Q(tx_done),
	.D(\tx/n138 ),
	.CLK(n15));
   DFFNEGX1 \tx/next_tstate_reg[1]  (.Q(\tx/next_tstate [1]),
	.D(\tx/N78 ),
	.CLK(clka));
   DFFNEGX1 \tx/tstate_reg[2]  (.Q(tstate[2]),
	.D(\tx/n135 ),
	.CLK(n15));
   DFFNEGX1 \tx/next_tstate_reg[2]  (.Q(\tx/next_tstate [2]),
	.D(\tx/N79 ),
	.CLK(clka));
   DFFNEGX1 \tx/tstate_reg[0]  (.Q(tstate[0]),
	.D(\tx/n137 ),
	.CLK(n15));
   DFFNEGX1 \tx/next_tstate_reg[0]  (.Q(\tx/next_tstate [0]),
	.D(\tx/N77 ),
	.CLK(clka));
   DFFNEGX1 \tx/tx_busy_reg  (.Q(tx_busy),
	.D(\tx/n143 ),
	.CLK(n15));
   DFFNEGX1 \tx/tcount_reg[3]  (.Q(tcount[3]),
	.D(\tx/n142 ),
	.CLK(n15));
   DFFNEGX1 \tx/tcount_reg[0]  (.Q(tcount[0]),
	.D(\tx/n144 ),
	.CLK(n15));
   OAI21X1 \rx/U150  (.Y(\rx/n124 ),
	.C(\rx/n49 ),
	.B(\rx/n52 ),
	.A(rstate[2]));
   NOR2X1 \rx/U149  (.Y(\rx/n126 ),
	.B(rstate[2]),
	.A(rx_busy));
   NAND3X1 \rx/U148  (.Y(\rx/n125 ),
	.C(\rx/n126 ),
	.B(\rx/n50 ),
	.A(rstate[1]));
   OR2X1 \rx/U147  (.Y(\rx/n120 ),
	.B(reset),
	.A(rstate[3]));
   AOI21X1 \rx/U146  (.Y(\rx/N77 ),
	.C(\rx/n120 ),
	.B(\rx/n125 ),
	.A(\rx/n124 ));
   NAND3X1 \rx/U145  (.Y(\rx/n123 ),
	.C(rx_rdy),
	.B(\rx/n49 ),
	.A(rstate[0]));
   OAI21X1 \rx/U144  (.Y(\rx/n122 ),
	.C(\rx/n123 ),
	.B(\rx/n49 ),
	.A(rstate[0]));
   NAND2X1 \rx/U143  (.Y(\rx/n121 ),
	.B(\rx/n48 ),
	.A(\rx/n122 ));
   NOR2X1 \rx/U142  (.Y(\rx/N78 ),
	.B(\rx/n121 ),
	.A(\rx/n120 ));
   NAND3X1 \rx/U141  (.Y(\rx/n118 ),
	.C(rstate[0]),
	.B(\rx/n48 ),
	.A(rstate[1]));
   NAND3X1 \rx/U140  (.Y(\rx/n119 ),
	.C(rstate[2]),
	.B(\rx/n49 ),
	.A(\rx/n50 ));
   AOI21X1 \rx/U139  (.Y(\rx/N79 ),
	.C(\rx/n120 ),
	.B(\rx/n119 ),
	.A(\rx/n118 ));
   NAND3X1 \rx/U138  (.Y(\rx/n63 ),
	.C(\rx/next_rstate [2]),
	.B(\rx/n30 ),
	.A(\rx/next_rstate [0]));
   NOR2X1 \rx/U137  (.Y(\rx/n117 ),
	.B(\rx/n28 ),
	.A(\rx/n29 ));
   NAND3X1 \rx/U136  (.Y(\rx/n77 ),
	.C(\rx/next_rstate [2]),
	.B(\rx/n30 ),
	.A(\rx/n31 ));
   NAND3X1 \rx/U135  (.Y(\rx/n110 ),
	.C(\rx/n31 ),
	.B(\rx/n28 ),
	.A(\rx/n30 ));
   OAI22X1 \rx/U131  (.Y(\rx/n152 ),
	.D(\rx/n50 ),
	.C(\rx/n66 ),
	.B(\rx/n31 ),
	.A(\rx/n15 ));
   NAND3X1 \rx/U130  (.Y(\rx/n79 ),
	.C(\rx/next_rstate [1]),
	.B(\rx/n28 ),
	.A(\rx/n31 ));
   NAND2X1 \rx/U129  (.Y(\rx/n84 ),
	.B(rcount[1]),
	.A(rcount[2]));
   OAI21X1 \rx/U127  (.Y(\rx/n114 ),
	.C(\rx/n106 ),
	.B(\rx/n79 ),
	.A(rcount[0]));
   AOI21X1 \rx/U126  (.Y(\rx/n115 ),
	.C(\rx/n114 ),
	.B(\rx/n84 ),
	.A(\rx/n27 ));
   NOR2X1 \rx/U125  (.Y(\rx/n108 ),
	.B(\rx/n14 ),
	.A(\rx/n79 ));
   NAND2X1 \rx/U124  (.Y(\rx/n113 ),
	.B(rcount[0]),
	.A(\rx/n108 ));
   NAND3X1 \rx/U123  (.Y(\rx/n116 ),
	.C(\rx/n11 ),
	.B(\rx/n32 ),
	.A(\rx/n35 ));
   OAI21X1 \rx/U122  (.Y(\rx/n151 ),
	.C(\rx/n116 ),
	.B(\rx/n32 ),
	.A(\rx/n115 ));
   OAI22X1 \rx/U121  (.Y(\rx/n150 ),
	.D(\rx/n13 ),
	.C(rcount[0]),
	.B(\rx/n38 ),
	.A(\rx/n106 ));
   OAI22X1 \rx/U120  (.Y(\rx/n149 ),
	.D(\rx/n113 ),
	.C(rcount[1]),
	.B(\rx/n36 ),
	.A(\rx/n10 ));
   NAND2X1 \rx/U119  (.Y(\rx/n93 ),
	.B(\rx/n34 ),
	.A(rcount[1]));
   NAND2X1 \rx/U118  (.Y(\rx/n102 ),
	.B(\rx/n36 ),
	.A(rcount[2]));
   OAI22X1 \rx/U117  (.Y(\rx/n112 ),
	.D(\rx/n79 ),
	.C(\rx/n102 ),
	.B(\rx/n93 ),
	.A(\rx/n113 ));
   OAI21X1 \rx/U116  (.Y(\rx/n148 ),
	.C(\rx/n12 ),
	.B(\rx/n34 ),
	.A(\rx/n10 ));
   NAND2X1 \rx/U115  (.Y(\rx/n111 ),
	.B(\rx/n14 ),
	.A(rx_idle));
   OAI21X1 \rx/U114  (.Y(\rx/n147 ),
	.C(\rx/n111 ),
	.B(\rx/n110 ),
	.A(\rx/n14 ));
   NAND2X1 \rx/U113  (.Y(\rx/n88 ),
	.B(\rx/n33 ),
	.A(rcount[0]));
   NOR2X1 \rx/U112  (.Y(\rx/n109 ),
	.B(\rx/n35 ),
	.A(rcount[3]));
   NAND3X1 \rx/U111  (.Y(\rx/n107 ),
	.C(\rx/n109 ),
	.B(\rx/n88 ),
	.A(\rx/n108 ));
   OAI21X1 \rx/U110  (.Y(\rx/n146 ),
	.C(\rx/n107 ),
	.B(\rx/n46 ),
	.A(\rx/n106 ));
   NAND2X1 \rx/U109  (.Y(\rx/n105 ),
	.B(\rx/n34 ),
	.A(\rx/n36 ));
   NAND2X1 \rx/U107  (.Y(\rx/n94 ),
	.B(rcount[0]),
	.A(\rx/n23 ));
   OAI21X1 \rx/U106  (.Y(\rx/n97 ),
	.C(\rx/n110 ),
	.B(\rx/n94 ),
	.A(\rx/n105 ));
   AOI22X1 \rx/U105  (.Y(\rx/n104 ),
	.D(rx_data[3]),
	.C(\rx/n38 ),
	.B(rcount[0]),
	.A(rx_data[4]));
   AOI22X1 \rx/U104  (.Y(\rx/n98 ),
	.D(\rx/n37 ),
	.C(rcount[1]),
	.B(\rx/n36 ),
	.A(rx_data[2]));
   NAND2X1 \rx/U103  (.Y(\rx/n103 ),
	.B(\rx/n35 ),
	.A(rx_data[7]));
   OAI21X1 \rx/U102  (.Y(\rx/n101 ),
	.C(\rx/n103 ),
	.B(\rx/n102 ),
	.A(\rx/n51 ));
   AOI22X1 \rx/U101  (.Y(\rx/n99 ),
	.D(\rx/n38 ),
	.C(\rx/n101 ),
	.B(rcount[0]),
	.A(\rx/n100 ));
   OAI21X1 \rx/U100  (.Y(\rx/n83 ),
	.C(\rx/n99 ),
	.B(\rx/n98 ),
	.A(rcount[2]));
   NAND2X1 \rx/U99  (.Y(\rx/n86 ),
	.B(\rx/n83 ),
	.A(\rx/n27 ));
   OAI22X1 \rx/U98  (.Y(\rx/n145 ),
	.D(\rx/n97 ),
	.C(\rx/n44 ),
	.B(\rx/n86 ),
	.A(\rx/n17 ));
   NAND2X1 \rx/U97  (.Y(\rx/n96 ),
	.B(\rx/n38 ),
	.A(\rx/n23 ));
   OAI21X1 \rx/U96  (.Y(\rx/n95 ),
	.C(\rx/n110 ),
	.B(\rx/n96 ),
	.A(\rx/n93 ));
   OAI22X1 \rx/U95  (.Y(\rx/n144 ),
	.D(\rx/n95 ),
	.C(\rx/n43 ),
	.B(\rx/n86 ),
	.A(\rx/n18 ));
   OAI21X1 \rx/U94  (.Y(\rx/n92 ),
	.C(\rx/n110 ),
	.B(\rx/n94 ),
	.A(\rx/n93 ));
   OAI22X1 \rx/U93  (.Y(\rx/n143 ),
	.D(\rx/n92 ),
	.C(\rx/n42 ),
	.B(\rx/n86 ),
	.A(\rx/n19 ));
   NAND2X1 \rx/U92  (.Y(\rx/n91 ),
	.B(\rx/n38 ),
	.A(\rx/n33 ));
   OAI21X1 \rx/U91  (.Y(\rx/n90 ),
	.C(\rx/n110 ),
	.B(\rx/n91 ),
	.A(\rx/n89 ));
   OAI22X1 \rx/U90  (.Y(\rx/n142 ),
	.D(\rx/n90 ),
	.C(\rx/n41 ),
	.B(\rx/n86 ),
	.A(\rx/n20 ));
   OAI21X1 \rx/U89  (.Y(\rx/n87 ),
	.C(\rx/n110 ),
	.B(\rx/n89 ),
	.A(\rx/n88 ));
   OAI22X1 \rx/U88  (.Y(\rx/n141 ),
	.D(\rx/n87 ),
	.C(\rx/n40 ),
	.B(\rx/n86 ),
	.A(\rx/n21 ));
   NAND3X1 \rx/U86  (.Y(\rx/n65 ),
	.C(\rx/n28 ),
	.B(\rx/next_rstate [0]),
	.A(\rx/next_rstate [1]));
   NAND2X1 \rx/U85  (.Y(\rx/n78 ),
	.B(\rx/n65 ),
	.A(\rx/n14 ));
   NAND2X1 \rx/U84  (.Y(\rx/n81 ),
	.B(\rx/n32 ),
	.A(\rx/n38 ));
   OR2X1 \rx/U83  (.Y(\rx/n82 ),
	.B(\rx/n84 ),
	.A(\rx/n83 ));
   OAI21X1 \rx/U82  (.Y(\rx/n80 ),
	.C(\rx/n78 ),
	.B(\rx/n82 ),
	.A(\rx/n81 ));
   OAI22X1 \rx/U81  (.Y(\rx/n140 ),
	.D(\rx/n80 ),
	.C(\rx/n79 ),
	.B(\rx/n78 ),
	.A(\rx/n39 ));
   XOR2X1 \rx/U80  (.Y(\rx/n75 ),
	.B(\rx/rtmpout [5]),
	.A(rx_data[5]));
   XOR2X1 \rx/U79  (.Y(\rx/n76 ),
	.B(\rx/rtmpout [6]),
	.A(rx_data[6]));
   NOR2X1 \rx/U78  (.Y(\rx/n70 ),
	.B(\rx/n76 ),
	.A(\rx/n75 ));
   XOR2X1 \rx/U77  (.Y(\rx/n71 ),
	.B(rx_data[4]),
	.A(\rx/n42 ));
   XOR2X1 \rx/U76  (.Y(\rx/n73 ),
	.B(\rx/rtmpout [2]),
	.A(rx_data[2]));
   XOR2X1 \rx/U75  (.Y(\rx/n74 ),
	.B(\rx/rtmpout [3]),
	.A(rx_data[3]));
   NOR2X1 \rx/U74  (.Y(\rx/n72 ),
	.B(\rx/n74 ),
	.A(\rx/n73 ));
   NAND3X1 \rx/U73  (.Y(\rx/n69 ),
	.C(\rx/n72 ),
	.B(\rx/n71 ),
	.A(\rx/n70 ));
   AOI22X1 \rx/U72  (.Y(\rx/n68 ),
	.D(\rx/n26 ),
	.C(rx_data[0]),
	.B(\rx/n69 ),
	.A(\rx/n25 ));
   OAI22X1 \rx/U71  (.Y(\rx/n139 ),
	.D(\rx/n68 ),
	.C(\rx/n16 ),
	.B(\rx/n67 ),
	.A(\rx/n45 ));
   OAI22X1 \rx/U70  (.Y(\rx/n138 ),
	.D(\rx/n49 ),
	.C(\rx/n66 ),
	.B(\rx/n30 ),
	.A(\rx/n15 ));
   OAI22X1 \rx/U69  (.Y(\rx/n137 ),
	.D(\rx/n48 ),
	.C(\rx/n66 ),
	.B(\rx/n28 ),
	.A(\rx/n15 ));
   OAI21X1 \rx/U68  (.Y(\rx/n135 ),
	.C(\rx/n65 ),
	.B(\rx/n47 ),
	.A(\rx/n26 ));
   NAND2X1 \rx/U66  (.Y(\rx/n53 ),
	.B(\rx/n62 ),
	.A(\rx/n29 ));
   NAND2X1 \rx/U65  (.Y(\rx/n61 ),
	.B(\rx/n9 ),
	.A(rx_out[0]));
   OAI21X1 \rx/U64  (.Y(\rx/n134 ),
	.C(\rx/n61 ),
	.B(\rx/n45 ),
	.A(\rx/n53 ));
   NAND2X1 \rx/U63  (.Y(\rx/n60 ),
	.B(\rx/n9 ),
	.A(rx_out[1]));
   OAI21X1 \rx/U62  (.Y(\rx/n133 ),
	.C(\rx/n60 ),
	.B(\rx/n47 ),
	.A(\rx/n53 ));
   NAND2X1 \rx/U61  (.Y(\rx/n59 ),
	.B(\rx/n9 ),
	.A(rx_out[2]));
   OAI21X1 \rx/U60  (.Y(\rx/n132 ),
	.C(\rx/n59 ),
	.B(\rx/n44 ),
	.A(\rx/n53 ));
   NAND2X1 \rx/U59  (.Y(\rx/n58 ),
	.B(\rx/n9 ),
	.A(rx_out[3]));
   OAI21X1 \rx/U58  (.Y(\rx/n131 ),
	.C(\rx/n58 ),
	.B(\rx/n43 ),
	.A(\rx/n53 ));
   NAND2X1 \rx/U57  (.Y(\rx/n57 ),
	.B(\rx/n9 ),
	.A(rx_out[4]));
   OAI21X1 \rx/U56  (.Y(\rx/n130 ),
	.C(\rx/n57 ),
	.B(\rx/n42 ),
	.A(\rx/n53 ));
   NAND2X1 \rx/U55  (.Y(\rx/n56 ),
	.B(\rx/n9 ),
	.A(rx_out[5]));
   OAI21X1 \rx/U54  (.Y(\rx/n129 ),
	.C(\rx/n56 ),
	.B(\rx/n41 ),
	.A(\rx/n53 ));
   NAND2X1 \rx/U53  (.Y(\rx/n55 ),
	.B(\rx/n9 ),
	.A(rx_out[6]));
   OAI21X1 \rx/U52  (.Y(\rx/n128 ),
	.C(\rx/n55 ),
	.B(\rx/n40 ),
	.A(\rx/n53 ));
   NAND2X1 \rx/U51  (.Y(\rx/n54 ),
	.B(\rx/n9 ),
	.A(rx_out[7]));
   OAI21X1 \rx/U50  (.Y(\rx/n127 ),
	.C(\rx/n54 ),
	.B(\rx/n39 ),
	.A(\rx/n53 ));
   INVX2 \rx/U49  (.Y(\rx/n52 ),
	.A(rx_rdy));
   INVX2 \rx/U48  (.Y(\rx/n51 ),
	.A(rx_data[5]));
   INVX2 \rx/U47  (.Y(\rx/n50 ),
	.A(rstate[0]));
   INVX2 \rx/U46  (.Y(\rx/n49 ),
	.A(rstate[1]));
   INVX2 \rx/U45  (.Y(\rx/n48 ),
	.A(rstate[2]));
   INVX2 \rx/U44  (.Y(\rx/n47 ),
	.A(rx_done));
   INVX2 \rx/U43  (.Y(\rx/n46 ),
	.A(rx_busy));
   INVX2 \rx/U42  (.Y(\rx/n45 ),
	.A(rx_error));
   INVX2 \rx/U41  (.Y(\rx/n44 ),
	.A(\rx/rtmpout [2]));
   INVX2 \rx/U40  (.Y(\rx/n43 ),
	.A(\rx/rtmpout [3]));
   INVX2 \rx/U39  (.Y(\rx/n42 ),
	.A(\rx/rtmpout [4]));
   INVX2 \rx/U38  (.Y(\rx/n41 ),
	.A(\rx/rtmpout [5]));
   INVX2 \rx/U37  (.Y(\rx/n40 ),
	.A(\rx/rtmpout [6]));
   INVX2 \rx/U36  (.Y(\rx/n39 ),
	.A(\rx/rtmpout [7]));
   INVX2 \rx/U35  (.Y(\rx/n38 ),
	.A(rcount[0]));
   INVX2 \rx/U34  (.Y(\rx/n37 ),
	.A(\rx/n104 ));
   INVX2 \rx/U33  (.Y(\rx/n36 ),
	.A(rcount[1]));
   INVX2 \rx/U32  (.Y(\rx/n35 ),
	.A(\rx/n84 ));
   INVX2 \rx/U31  (.Y(\rx/n34 ),
	.A(rcount[2]));
   INVX2 \rx/U30  (.Y(\rx/n33 ),
	.A(\rx/n102 ));
   INVX2 \rx/U29  (.Y(\rx/n32 ),
	.A(rcount[3]));
   INVX2 \rx/U28  (.Y(\rx/n31 ),
	.A(\rx/next_rstate [0]));
   INVX2 \rx/U27  (.Y(\rx/n30 ),
	.A(\rx/next_rstate [1]));
   INVX2 \rx/U26  (.Y(\rx/n29 ),
	.A(\rx/n63 ));
   INVX2 \rx/U25  (.Y(\rx/n28 ),
	.A(\rx/next_rstate [2]));
   INVX2 \rx/U24  (.Y(\rx/n27 ),
	.A(\rx/n79 ));
   INVX2 \rx/U23  (.Y(\rx/n26 ),
	.A(\rx/n110 ));
   INVX2 \rx/U22  (.Y(\rx/n25 ),
	.A(\rx/n77 ));
   INVX2 \rx/U21  (.Y(\rx/n23 ),
	.A(\rx/n89 ));
   INVX2 \rx/U19  (.Y(\rx/n21 ),
	.A(\rx/n87 ));
   INVX2 \rx/U18  (.Y(\rx/n20 ),
	.A(\rx/n90 ));
   INVX2 \rx/U17  (.Y(\rx/n19 ),
	.A(\rx/n92 ));
   INVX2 \rx/U16  (.Y(\rx/n18 ),
	.A(\rx/n95 ));
   INVX2 \rx/U15  (.Y(\rx/n17 ),
	.A(\rx/n97 ));
   INVX2 \rx/U14  (.Y(\rx/n16 ),
	.A(\rx/n67 ));
   INVX2 \rx/U13  (.Y(\rx/n15 ),
	.A(\rx/n66 ));
   INVX2 \rx/U12  (.Y(\rx/n14 ),
	.A(\rx/n106 ));
   INVX2 \rx/U11  (.Y(\rx/n13 ),
	.A(\rx/n108 ));
   INVX2 \rx/U10  (.Y(\rx/n12 ),
	.A(\rx/n112 ));
   INVX2 \rx/U9  (.Y(\rx/n11 ),
	.A(\rx/n113 ));
   INVX2 \rx/U8  (.Y(\rx/n10 ),
	.A(\rx/n114 ));
   INVX2 \rx/U7  (.Y(\rx/n9 ),
	.A(\rx/n62 ));
   AND2X2 \rx/U6  (.Y(\rx/n100 ),
	.B(\rx/n33 ),
	.A(rx_data[6]));
   AND2X2 \rx/U5  (.Y(\rx/n136 ),
	.B(rstate[3]),
	.A(\rx/n15 ));
   DFFNEGX1 \rx/rx_out_reg[2]  (.Q(rx_out[2]),
	.D(\rx/n132 ),
	.CLK(n14));
   DFFNEGX1 \rx/rx_out_reg[0]  (.Q(rx_out[0]),
	.D(\rx/n134 ),
	.CLK(n14));
   DFFNEGX1 \rx/rx_error_reg  (.Q(rx_error),
	.D(\rx/n139 ),
	.CLK(n14));
   DFFNEGX1 \rx/rtmpout_reg[2]  (.Q(\rx/rtmpout [2]),
	.D(\rx/n145 ),
	.CLK(n14));
   DFFNEGX1 \rx/rx_out_reg[3]  (.Q(rx_out[3]),
	.D(\rx/n131 ),
	.CLK(n14));
   DFFNEGX1 \rx/rtmpout_reg[3]  (.Q(\rx/rtmpout [3]),
	.D(\rx/n144 ),
	.CLK(n14));
   DFFNEGX1 \rx/rx_out_reg[4]  (.Q(rx_out[4]),
	.D(\rx/n130 ),
	.CLK(n14));
   DFFNEGX1 \rx/rtmpout_reg[4]  (.Q(\rx/rtmpout [4]),
	.D(\rx/n143 ),
	.CLK(n14));
   DFFNEGX1 \rx/rx_out_reg[5]  (.Q(rx_out[5]),
	.D(\rx/n129 ),
	.CLK(n14));
   DFFNEGX1 \rx/rtmpout_reg[5]  (.Q(\rx/rtmpout [5]),
	.D(\rx/n142 ),
	.CLK(n14));
   DFFNEGX1 \rx/rx_out_reg[6]  (.Q(rx_out[6]),
	.D(\rx/n128 ),
	.CLK(n14));
   DFFNEGX1 \rx/rtmpout_reg[6]  (.Q(\rx/rtmpout [6]),
	.D(\rx/n141 ),
	.CLK(n14));
   DFFNEGX1 \rx/rx_out_reg[7]  (.Q(rx_out[7]),
	.D(\rx/n127 ),
	.CLK(n14));
   DFFNEGX1 \rx/rtmpout_reg[7]  (.Q(\rx/rtmpout [7]),
	.D(\rx/n140 ),
	.CLK(n13));
   DFFNEGX1 \rx/rx_busy_reg  (.Q(rx_busy),
	.D(\rx/n146 ),
	.CLK(n13));
   DFFNEGX1 \rx/rcount_reg[3]  (.Q(rcount[3]),
	.D(\rx/n151 ),
	.CLK(n13));
   DFFNEGX1 \rx/rx_idle_reg  (.Q(rx_idle),
	.D(\rx/n147 ),
	.CLK(n13));
   DFFNEGX1 \rx/rcount_reg[2]  (.Q(rcount[2]),
	.D(\rx/n148 ),
	.CLK(n13));
   DFFNEGX1 \rx/rcount_reg[1]  (.Q(rcount[1]),
	.D(\rx/n149 ),
	.CLK(n13));
   DFFNEGX1 \rx/rcount_reg[0]  (.Q(rcount[0]),
	.D(\rx/n150 ),
	.CLK(n13));
   DFFNEGX1 \rx/rx_out_reg[1]  (.Q(rx_out[1]),
	.D(\rx/n133 ),
	.CLK(n13));
   DFFNEGX1 \rx/rx_done_reg  (.Q(rx_done),
	.D(\rx/n135 ),
	.CLK(n13));
   DFFNEGX1 \rx/rstate_reg[3]  (.Q(rstate[3]),
	.D(\rx/n136 ),
	.CLK(n13));
   DFFNEGX1 \rx/next_rstate_reg[0]  (.Q(\rx/next_rstate [0]),
	.D(\rx/N77 ),
	.CLK(clka));
   DFFNEGX1 \rx/rstate_reg[1]  (.Q(rstate[1]),
	.D(\rx/n138 ),
	.CLK(n13));
   DFFNEGX1 \rx/next_rstate_reg[1]  (.Q(\rx/next_rstate [1]),
	.D(\rx/N78 ),
	.CLK(clka));
   DFFNEGX1 \rx/rstate_reg[2]  (.Q(rstate[2]),
	.D(\rx/n137 ),
	.CLK(n13));
   DFFNEGX1 \rx/next_rstate_reg[2]  (.Q(\rx/next_rstate [2]),
	.D(\rx/N79 ),
	.CLK(clka));
   DFFNEGX1 \rx/rstate_reg[0]  (.Q(rstate[0]),
	.D(\rx/n152 ),
	.CLK(n13));
   NAND2X1 \dp1/d1/U14  (.Y(\dp1/d1/n3 ),
	.B(n20),
	.A(tx_done));
   NAND2X1 \dp1/d1/U13  (.Y(\dp1/d1/N3 ),
	.B(\dp1/d1/n3 ),
	.A(n20));
   INVX2 \dp1/d1/U11  (.Y(\dp1/d1/n1 ),
	.A(\dp1/d1/n3 ));
   AND2X2 \dp1/d1/U10  (.Y(\dp1/d1/N10 ),
	.B(\dp1/d1/n1 ),
	.A(tx_out[6]));
   AND2X2 \dp1/d1/U9  (.Y(\dp1/d1/N11 ),
	.B(\dp1/d1/n1 ),
	.A(tx_out[7]));
   AND2X2 \dp1/d1/U8  (.Y(\dp1/d1/N4 ),
	.B(\dp1/d1/n1 ),
	.A(tx_out[0]));
   AND2X2 \dp1/d1/U6  (.Y(\dp1/d1/N6 ),
	.B(\dp1/d1/n1 ),
	.A(tx_out[2]));
   AND2X2 \dp1/d1/U5  (.Y(\dp1/d1/N7 ),
	.B(\dp1/d1/n1 ),
	.A(tx_out[3]));
   AND2X2 \dp1/d1/U4  (.Y(\dp1/d1/N8 ),
	.B(\dp1/d1/n1 ),
	.A(tx_out[4]));
   AND2X2 \dp1/d1/U3  (.Y(\dp1/d1/N9 ),
	.B(\dp1/d1/n1 ),
	.A(tx_out[5]));
   LATCH \dp1/d1/q_reg[0]  (.Q(rx_data[0]),
	.D(\dp1/d1/N4 ),
	.CLK(\dp1/d1/N3 ));
   LATCH \dp1/d1/q_reg[2]  (.Q(rx_data[2]),
	.D(\dp1/d1/N6 ),
	.CLK(\dp1/d1/N3 ));
   LATCH \dp1/d1/q_reg[3]  (.Q(rx_data[3]),
	.D(\dp1/d1/N7 ),
	.CLK(\dp1/d1/N3 ));
   LATCH \dp1/d1/q_reg[4]  (.Q(rx_data[4]),
	.D(\dp1/d1/N8 ),
	.CLK(\dp1/d1/N3 ));
   LATCH \dp1/d1/q_reg[5]  (.Q(rx_data[5]),
	.D(\dp1/d1/N9 ),
	.CLK(\dp1/d1/N3 ));
   LATCH \dp1/d1/q_reg[6]  (.Q(rx_data[6]),
	.D(\dp1/d1/N10 ),
	.CLK(\dp1/d1/N3 ));
   LATCH \dp1/d1/q_reg[7]  (.Q(rx_data[7]),
	.D(\dp1/d1/N11 ),
	.CLK(\dp1/d1/N3 ));
   NAND2X1 \dp2/d1/U14  (.Y(n21),
	.B(n20),
	.A(rx_done));
   NAND2X1 \dp2/d1/U13  (.Y(\dp2/d1/N3 ),
	.B(n21),
	.A(n20));
   INVX2 \dp2/d1/U12  (.Y(n20),
	.A(reset));
   INVX2 \dp2/d1/U11  (.Y(n19),
	.A(n21));
   AND2X2 \dp2/d1/U10  (.Y(\dp2/d1/N10 ),
	.B(n19),
	.A(rx_out[6]));
   AND2X2 \dp2/d1/U9  (.Y(\dp2/d1/N11 ),
	.B(n19),
	.A(rx_out[7]));
   AND2X2 \dp2/d1/U8  (.Y(\dp2/d1/N4 ),
	.B(n19),
	.A(rx_out[0]));
   AND2X2 \dp2/d1/U7  (.Y(\dp2/d1/N5 ),
	.B(n19),
	.A(rx_out[1]));
   AND2X2 \dp2/d1/U6  (.Y(\dp2/d1/N6 ),
	.B(n19),
	.A(rx_out[2]));
   AND2X2 \dp2/d1/U5  (.Y(\dp2/d1/N7 ),
	.B(n19),
	.A(rx_out[3]));
   AND2X2 \dp2/d1/U4  (.Y(\dp2/d1/N8 ),
	.B(n19),
	.A(rx_out[4]));
   AND2X2 \dp2/d1/U3  (.Y(\dp2/d1/N9 ),
	.B(n19),
	.A(rx_out[5]));
   LATCH \dp2/d1/q_reg[0]  (.Q(rxrxout[0]),
	.D(\dp2/d1/N4 ),
	.CLK(\dp2/d1/N3 ));
   LATCH \dp2/d1/q_reg[1]  (.Q(rxrxout[1]),
	.D(\dp2/d1/N5 ),
	.CLK(\dp2/d1/N3 ));
   LATCH \dp2/d1/q_reg[2]  (.Q(rxrxout[2]),
	.D(\dp2/d1/N6 ),
	.CLK(\dp2/d1/N3 ));
   LATCH \dp2/d1/q_reg[3]  (.Q(rxrxout[3]),
	.D(\dp2/d1/N7 ),
	.CLK(\dp2/d1/N3 ));
   LATCH \dp2/d1/q_reg[4]  (.Q(rxrxout[4]),
	.D(\dp2/d1/N8 ),
	.CLK(\dp2/d1/N3 ));
   LATCH \dp2/d1/q_reg[5]  (.Q(rxrxout[5]),
	.D(\dp2/d1/N9 ),
	.CLK(\dp2/d1/N3 ));
   LATCH \dp2/d1/q_reg[6]  (.Q(rxrxout[6]),
	.D(\dp2/d1/N10 ),
	.CLK(\dp2/d1/N3 ));
   LATCH \dp2/d1/q_reg[7]  (.Q(rxrxout[7]),
	.D(\dp2/d1/N11 ),
	.CLK(\dp2/d1/N3 ));
   INVX2 U14 (.Y(n13),
	.A(n17));
   INVX2 U15 (.Y(n14),
	.A(n17));
   INVX2 U16 (.Y(n15),
	.A(n16));
   BUFX2 U17 (.Y(n17),
	.A(n18));
   BUFX2 U18 (.Y(n16),
	.A(n18));
   INVX2 U19 (.Y(n18),
	.A(clkb));
   NAND2X1 U20 (.Y(\tx/n78 ),
	.B(\tx/n24 ),
	.A(\tx/n34 ));
   NAND2X1 U21 (.Y(\rx/n89 ),
	.B(\rx/n27 ),
	.A(\rx/n32 ));
   INVX2 U22 (.Y(\tx/n95 ),
	.A(\tx/n97 ));
   NAND2X1 U23 (.Y(\tx/n107 ),
	.B(\tx/n97 ),
	.A(\tx/n83 ));
   NAND2X1 U24 (.Y(\tx/n58 ),
	.B(\tx/n97 ),
	.A(\tx/n59 ));
   NAND2X1 U25 (.Y(\tx/n93 ),
	.B(\tx/n17 ),
	.A(\tx/n94 ));
   NAND2X1 U26 (.Y(\tx/n56 ),
	.B(\tx/n97 ),
	.A(\tx/n57 ));
   NAND2X1 U27 (.Y(\rx/n67 ),
	.B(\rx/n110 ),
	.A(\rx/n77 ));
   NAND2X1 U28 (.Y(\rx/n66 ),
	.B(\rx/n16 ),
	.A(\rx/n117 ));
   NAND2X1 U29 (.Y(\rx/n106 ),
	.B(\rx/n110 ),
	.A(\rx/n79 ));
   NAND2X1 U30 (.Y(\rx/n62 ),
	.B(\rx/n110 ),
	.A(\rx/n63 ));
endmodule

